### ISSUE TITLE
Unable to see logs

### ISSUE THREAD

**Issue by sheminasalam** [Banditen01/vintage_theme#1]
Green color of logs texts are not visible

**Comment by Banditen01** [comment]
Ok, tx for info, will check and report back

**Comment by Banditen01** [comment]
> Green color of logs texts are not visible
Tried to recreate the problem, but it works for me? 
What browser do You use? 
Have you tried to refresh/clean cache?

**Comment by Banditen01** [comment]
@sheminasalam 

Tried to recreate the problem, but it works for me? 
What browser do You use? 
Have you tried to refresh/clean cache?

**Comment by sheminasalam** [comment]
I am using chrome and I have done cache clearing but the problem persists. I have attached a image of what I get. 
![image](https://user-images.githubusercontent.com/45196177/83856276-ea591280-a736-11ea-92a2-e511a4e3c425.png)

**Comment by Banditen01** [comment]
> I am using chrome and I have done cache clearing but the problem persists. I have attached a image of what I get.
> ![image](https://user-images.githubusercontent.com/45196177/83856276-ea591280-a736-11ea-92a2-e511a4e3c425.png)

Ok, thanks and you are using latest version of the theme?

I can tell from your image that you are using Hassio, I'm not, maybe thats why, I checked my logs via Developer Tools and there it works (attached image).

I will check this (at work at the moment) will come back to you asap.
![abc123](https://user-images.githubusercontent.com/16663632/83859332-0bf9d000-a71e-11ea-88ae-ce31b281c326.jpg)

**Comment by sheminasalam** [comment]
thanks appreciate the good work

**Comment by Banditen01** [comment]
Fixed!!
